<?php

namespace AppBundle\Repository;

/**
 * CartlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartlineRepository extends \Doctrine\ORM\EntityRepository
{
}
