<?php

namespace AppBundle\Repository;

/**
 * CartlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartlineRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByCart($cartId)
    {
        $query = $this->entityManager
        ->createQuery('SELECT cl
        FROM AppBundle\Entity\Cartline cl 
        WHERE c.cart=:cartId');
        $query->setParameter('cartId', $cartId);
        return $query->getResult();
    }
}
