<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository
{
    /**
    * @var EntityRepository
    */
    private $repository;
    
    /**
    * @var EntityManagerInterface
    */
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function generateRefCom()
    {
        $currentYear = new \Datetime('now');

        $query = $this->entityManager->createQuery(
            'SELECT MAX(c.refcom) AS ref FROM AppBundle:Commande c WHERE c.refcom LIKE :ref'
        );
        $query->setParameter('ref', $currentYear->format('y') . '-%');
        $result = $query->getOneOrNullResult();
        if ($result === null) {
            return $currentYear->format('y')."-00001";
        }
        $lastRef = intval(str_replace($currentYear->format('y')."-", "", $result['ref']));
        
        $newRef = strval($lastRef + 1);
        $newRefString = strval($newRef);
        $newRefString = str_pad($newRefString, 5, "0", STR_PAD_LEFT);
        
        return $currentYear->format('y')."-".$newRefString;
    }
    
    public function findByRef($ref)
    {
        $query = $this->entityManager->createQuery(
            'SELECT c FROM AppBundle:Commande c WHERE c.refcom LIKE :ref'
        );
        $query->setMaxResults(1);
        $query->setParameter('ref', $ref);
        return $query->getOneOrNullResult();
    }
}
