<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository
{
    /**
    * @var EntityRepository
    */
    private $repository;
    
    /**
    * @var EntityManagerInterface
    */
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function generateRefCom()
    {
        $currentYear = new \Datetime('now');

        $query = $this->entityManager->createQuery(
            'SELECT MAX(c.refcom) AS ref FROM AppBundle:Commande c WHERE c.refcom LIKE :ref'
        );
        $query->setParameter('ref', $currentYear->format('y') . '-%');
        $result = $query->getOneOrNullResult();

        dump($result);
        if ($result === null) {
            $newRefString = $currentYear->format('y')."-00001";
            return $newRefString;
        } else {
            $lastRef = str_replace($currentYear->format('y')."-", "", $result['ref']);
            $lastRef = intval($lastRef);
        
            $newRef = $lastRef + 1;
            $newRefString = strval($newRef);
            while (strlen($newRefString) < 5) {
                $newRefString = "0".$newRefString;
            }
    
            $newRefString = $currentYear->format('y')."-".$newRefString;
            
            return $newRefString;
        }
    }
}
