<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;

/**
 * DonRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonRRepository
{

    /**
    * @var EntityManagerInterface
    */
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    
    /**
    * Find last year's ref
    *
    */
    public function findLastRef($year)
    {
        $query = $this->entityManager
        ->createQuery('SELECT dr.refdon
        FROM AppBundle\Entity\DonR dr 
        WHERE dr.refdon LIKE :year
        ORDER BY dr.refdon DESC');
        $query->setParameter('year', $year.'-%')
        ->setMaxResults(1);
        $lastRef = $query->getOneOrNullResult();
        if (is_array($lastRef) && array_key_exists('refdon', $lastRef)) {
            return $lastRef['refdon'];
        }

        return null;
    }

    /**
     * Find by reference
     */
    public function findByRef($ref)
    {
        $query = $this->entityManager
        ->createQuery('SELECT dr
        FROM AppBundle\Entity\DonR dr 
        WHERE dr.refdon LIKE :ref');
        $query->setParameter('ref', $ref)
        ->setMaxResults(1);
        return $query->getOneOrNullResult();
    }
}
