<?php

namespace AppBundle\Repository;

use AppBundle\Entity\News;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNextByLocale($locale)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT n FROM AppBundle:News n WHERE n.locale = :locale AND n.stop >= :now ORDER BY n.start DESC'
        )
        ->setParameters(['locale' => $locale, 'now' => new \DateTime()])
        ->getResult();
    }

    public function findAllSorted(string $locale)
    {
        return $this->getEntityManager()->getRepository(News::class)->createQueryBuilder('n')
            ->andWhere('n.locale = :locale')
            ->orderBy('n.start', 'DESC')
            ->setParameters([
                'locale' => $locale,
            ])
            ->getQuery()->execute();
    }

    public function findForHomepage(string $locale, $limit = 3)
    {
        return $this->getEntityManager()->getRepository(News::class)->createQueryBuilder('n')
            ->where(':now BETWEEN n.start AND n.stop')
            ->andWhere('n.locale = :locale')
            ->orderBy('n.start', 'DESC')
            ->setParameters([
                'locale' => $locale,
                'now' => new \DateTime()
            ])
            ->setMaxResults($limit)
        ->getQuery()->execute();
    }
}
