<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNextByLocale($locale)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT n FROM AppBundle:News n WHERE n.locale = :locale AND n.start >= :now ORDER BY n.start DESC'
        )
        ->setParameters(['locale' => $locale, 'now' => new \DateTime()])
        ->getResult();
    }
}
