<?php

namespace AppBundle\Repository;

/**
 * PackagingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackagingRepository extends \Doctrine\ORM\EntityRepository
{
}
