<?php

namespace AppBundle\Repository;

use Gedmo\Sortable\Entity\Repository\SortableRepository;
use AppBundle\Entity\Speaker;

/**
 * SpeakerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeakerRepository extends SortableRepository
{
    public function findAllOrderByPos()
    {
        return $this->getEntityManager()
        ->createQuery('SELECT s FROM AppBundle:Speaker s
        ORDER BY s.position')
        ->getResult();
    }
}
