<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;

/**
 * TaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRepository extends \Doctrine\ORM\EntityRepository
{

    /**
    * @var EntityManagerInterface
    */
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function findTax($productType, $country)
    {
        $query = $this->entityManager
        ->createQuery('SELECT t 
        FROM AppBundle\Entity\Tax t 
        WHERE t.typPrd=:productType
        AND t.countries LIKE :country');
        $query->setParameters(['productType' => $productType, 'country' => '%'.$country.'%']);
        return $query->getOneOrNullResult();
    }
}
