<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use AppBundle\Entity\Cart;
use AppBundle\Entity\Produit;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TpaysRepository
{
    /**
    * @var EntityManagerInterface
    */
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
    * Find Tpays
    *
    * @return Tpays
    */
    public function findAllCountry()
    {
        $query = $this->entityManager
        ->createQuery('SELECT t FROM AppBundle\Entity\Tpays t');
        return $query->getResult();
    }
}
