<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use AppBundle\Entity\Cart;
use AppBundle\Entity\Produit;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TpaysRepository
{
    const EXCEPTION = [
        'Roche',
        'Font',
    ];

    /**
    * @var EntityManagerInterface
    */
    private $entityManager;
    
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    /**
    * Find Tpays
    *
    * @return Tpays
    */
    public function findAllCountry()
    {
        $query = $this->entityManager
        ->createQuery('SELECT t FROM AppBundle\Entity\Tpays t');
        return $query->getResult();
    }

    /**
    * Check Zipcode
    *
    * @return Bool
    */
    public function checkZipcode($country, $zipcode, $destliv)
    {
        if (in_array($destliv, $this::EXCEPTION)) {
            return true;
        }

        if (strlen($country) === 2) {
            $query = $this->entityManager
            ->createQuery('SELECT tp.nompays 
            FROM AppBundle\Entity\Tpays tp 
            WHERE tp.codpays=:country');
            $query->setParameter('country', $country);
            $result =  $query->getOneOrNullResult();
            $country = $result;
        }
 
        $query = $this->entityManager
        ->createQuery('SELECT tp.zipcodes 
        FROM AppBundle\Entity\Tpays tp 
        WHERE tp.nompays=:country');
        $query->setParameter('country', $country["nompays"]);
        $results =  $query->getOneOrNullResult();

        if ($results['zipcodes'] === null) {
            return true;
        }

        foreach ($results['zipcodes'] as $k => $result) {
            if ($zipcode >= $result[0] && $zipcode <= $result[1]) {
                return true;
            }
        }
        
        return false;
    }
}
