imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: fr
    files_directory: '%kernel.root_dir%/../web/uploads'
    locales: fr|en|es|de|it
    httpprotocol: http

framework:
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/assets/manifest.json'
    php_errors:
        log: true
    translator:
        fallbacks: ['fr']
        paths: ['%kernel.project_dir%/translations']
    serializer:
        enabled: true
    templating:
        engines: ['twig']

translation:
    locales: ['fr', 'es']
    configs:
        app:
            dirs: ["%kernel.root_dir%/Resources/views", "%kernel.project_dir%/src"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_dirs: [cache, data, logs]
    webui:
        enabled: true

# Twig Configuration
twig:
    cache: false
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locales: ['fr', 'en', 'es', 'de', 'it']
        kiwi_host: '%kiwi_host%'
    form_themes: ['bootstrap_4_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver: '%database_driver%'
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                logging: true

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
           gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                alias: GedmoLoggable
                is_bundle: false
        dql:
            string_functions:
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
                substring_index: DoctrineExtensions\Query\Mysql\SubstringIndex
                regexp: DoctrineExtensions\Query\Mysql\Regexp
                replace: DoctrineExtensions\Query\Mysql\Replace
                JSON_CONTAINS: Syslogic\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonContains
            datetime_functions:
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sortable: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sensio_framework_extra:
    request: { converters: true }
fos_rest:
    body_converter:
        enabled: true
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    serializer:
        serialize_null: true
    format_listener:
        rules:
        - { path: '^/api/file', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
        - { path: '^/api/(?!login)', priorities: ['json'], fallback_format: 'json' }
        - { path: '^/xhr', priorities: ['json'], fallback_format: 'json' }
        - { path: '/shop/(register|password-request)', priorities: ['json'], fallback_format: 'json' }
        - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        enabled: true
        persistence:
            orm:
                enabled: true
        auto_locale_pattern: true
        locales: ['fr', 'es']
        generic_controller: AppBundle:Default:showPage
        route_collection_limit: 200

nelmio_cors:
    paths:
      '^/(login|logout)':
          allow_origin: ['*']
          allow_headers: ['Content-Type']
          allow_methods: ['OPTIONS', 'POST', 'GET']
          allow_credentials: true
          max_age: 3600

doctrine_migrations:
    dir_name: "%kernel.root_dir%/doctrine_migrations"

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%upload_root_path%"
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        page_carousel_small:
            quality: 75
            filters:
                downscale:
                    max: [960, 960]
            post_processors:
                jpegoptim: { strip_all: true, progressive: true }
        page_carousel_full:
            quality: 75
            filters:
                downscale:
                    max: [2048, 1024]
            post_processors:
                jpegoptim: { strip_all: true, progressive: true }
        product_card:
            quality: 75
            filters:
                downscale:
                    max: [800, 500]
            post_processors:
                jpegoptim: { strip_all: true, progressive: true }
        product_carousel_small:
            quality: 75
            filters:
                downscale:
                    max: [500, 200]
            post_processors:
                jpegoptim: { strip_all: true, progressive: true }
        product_carousel_full:
            quality: 75
            filters:
                downscale:
                    max: [1600, 1000]
            post_processors:
                jpegoptim: { strip_all: true, progressive: true }
        product_highlight:
            quality: 75
            filters:
                downscale:
                    max: [2500, 1000]
            post_processors:
                jpegoptim: { strip_all: true, progressive: true }
